name: 'Check Files Changed'
description: 'Checks if certain files have changed between versions'
branding:
  icon: hash
  color: yellow
inputs:
  paths:
    description: 'Paths to check if files have changed'
    required: true
  version:
    description: 'Version to compare with. Pass "none" to simply use previous commit'
    required: false
outputs:
  changes:
    description: '''True'' if there are file changes, ''False'' otherwise.'
runs:
  using: 'node16'
  main: 'dist/index.js'
